### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cryptoida** [acidg/SecureBitcoinWalletJavaCardApplet#1]
At what stage is this project?
What cryptocurrencies wallets are supported ?

**Comment by acidg** [comment]
This was a project I made for university and it is finished/discontinued. The idea was to store the private key for a Bitcoin address in the smart card.

**Comment by cryptoida** [comment]
Is not full functional ?

**Comment by acidg** [comment]
As far as I remember, the prototype was kind of working. The code is licensed under Apache, so feel free to modify and use it :)
